### ISSUE TITLE
MrOver: aggregate incorrect as currencies in rows differ

### ISSUE THREAD

**Issue by Eddman** [Deutsche-Boerse-Risk/DAVe-UI#23]
![image](https://user-images.githubusercontent.com/209500/27374090-dada15c2-566a-11e7-8245-52e17e40994a.png)

**Comment by markadir** [comment]
@Eddman : Where does this come from?

**Comment by Eddman** [comment]
@markadir In the footer on the dashboard we have a single row where we calculate the sum of all values, but without currency conversion. This is obviously a bug.

**Comment by Eddman** [comment]
![image](https://user-images.githubusercontent.com/209500/29113580-b371b4ba-7cf1-11e7-8b95-60418db59ac0.png)

**Comment by markadir** [comment]
@Eddman  Should we close the issue and treat it in a more General way in Issue 42?

**Comment by Eddman** [comment]
@markadir Let's keep this issue as the #42 is a way to big. Let's treat #42 as a container for discussion and create a separate issues per screen/component. We already have #33 for dashboard and we should create one for the treemap...WDYT?

**Comment by hauehan** [comment]
The table willbe discussed in issue.The current issue willb e closed.
