### ISSUE TITLE
PoolMr: Use correct column lables

### ISSUE THREAD

**Issue by Eddman** [Deutsche-Boerse-Risk/DAVe-UI#25]
![image](https://user-images.githubusercontent.com/209500/27374213-50ced830-566b-11e7-83fc-d74b73cec1d3.png)

**Comment by markadir** [comment]
The below table would have the correct names:
| Collateral Pool    | Margin Currency  | Margin requirement in margin currency  | Cash Collateral 
| ------------- | ------------- |------------- | ------------- |
| XRPSIIWUGINYCW | EUR | 549,918,740 EUR | 247,677

**Comment by Eddman** [comment]
@zerola, @halajos Could you please answer @markadir question?

**Comment by PavlaSip** [comment]
@markadir @hauehan @iyigmel should we rather call it "Variation Premium Payment" instead of Variaitzon/Premium Margin cash flow in order to be consistent with the other views?

**Comment by hauehan** [comment]
@PavlaSip If it is consistent with outher sources then let's use Variation Premium Payment. Contentwise both would be fine.

**Comment by PavlaSip** [comment]
@Eddman Adam can you then please apply the name Variation Premium Payment instead of the Variation/Premium Margin cash flow? (see also the issue #36 )

**Comment by Eddman** [comment]
@PavlaSip Will do.

**Comment by Eddman** [comment]
@orsamir From @markadir:
```
One question: What is the table Name where you get the Adjusted Guarantee value from?
I would like to have a look and see if it's not Zero somewhere
```

**Comment by PavlaSip** [comment]
Just FYI the field Adjusted Guarantee will be deleted in the table in the database (so not sure if you will see it at all), as it is no longer used (has been put to 0 for the last few years). However, we should continue to show it to the members, as it also remains in the member reports.

**Comment by orsamir** [comment]
In Prisma the table is AssetCash (EUREX_PRISMA.F_FCT_ASSETCASH)

**Comment by markadir** [comment]
@PavlaSip : We don't Need to show a meaningles column (Adjusted Guarantee ). The aim is not to copy reports but to offer an easy way to get transparency on margins.

**Comment by Eddman** [comment]
@markadir Quick question: what about "Pool owner"? Should it be removed?

**Comment by iyigmel** [comment]
I would keep it for individual segregated pools

**Comment by markadir** [comment]
I would remove it since ist always the Clearing member. This column does not provide additional Information and hence polutes the view.

**Comment by Eddman** [comment]
@markadir, @iyigmel So should I keep it or remove it? :flushed:

**Comment by hauehan** [comment]
Keep pool owner as poolowner can be different then the CM.
