### ISSUE TITLE
Remove cent values from margin figures

### ISSUE THREAD

**Issue by markadir** [Deutsche-Boerse-Risk/DAVe-UI#32]
The Cent values have to be removed since it only adds to confusion, reduces clarity and uses valuable column space. There is no interest from the client perspective to see that his margin requirement is xxx hundred Million and ,05 Cents.

**Comment by Eddman** [comment]
@markadir in all screens/charts/tables?

**Comment by markadir** [comment]
Yes for all margin values on all Screens/tables/charts but not for Prices or FX rates.

**Comment by Eddman** [comment]
@markadir By "Prices" you mean? :smile:

**Comment by markadir** [comment]
I mean a Price of some security - it's mostly relevant for the Position table

**Comment by Eddman** [comment]
@markadir If there are only few that you want to keep...can you list them? Would help me much... Thanks.

**Comment by markadir** [comment]
Please remove cent values and round mathematically and round to 3 dec points in the following columns:
| No cent values         | Cent values 3 decimals          |
| ---------------         | -----------------------          |
| Premium Margin      | PremPay                               |
| Margin requirement | Variation Premium Payment  |
| Initial Margin  |  Current Liquidating Margin |
| Unadjusted Margin  | FX Rate  |
| Net position  | -  |
| EuroDelta  |  - |
| LA | -  |
| Position VaR  | - |
| Rho |  - |
| CorrBreak  |  - |
| LonOptCredit  | -  |
| Gamma  | -  |
| Vega  | -  |
| Theta  | -  |
|MVar  | -  |
| Liquidity Risk  | -  |
| Cash Collateral  | -  |
| Non Cash Collateral   | -  |

**Comment by Eddman** [comment]
In case of FX Rate we have now 10 decimals to be in line with Prisma.

**Comment by markadir** [comment]
We don't need to be in line with Prisma, since it's not a calculation module but a presentation Module. In Prisma it's done because with really big numbers if you convert with smaller precision the effect might be really big. For viewing 4 decimals is market standard.

**Comment by Eddman** [comment]
@markadir What should I understand under:
```
A column with last rlevant price in the position details report page has to be added and displayed using decimal values
```

**Comment by markadir** [comment]
It's a different issue. If you display EURODelta or EUROVega it's always related to a Price. Also the Margin figures, particularly Variation Margin or Premium. There is no column with a Price. So the Price of the FESX Sep17 contract is now: 3452. Hence I would like to see in my Position Details near the EURODelta Information also the Price which was used for this calculation.

**Comment by Eddman** [comment]
And the value of EURODelta or EUROVega should be without decimals. Right?

**Comment by markadir** [comment]
Right! They are big values. If you would be displaying analytical Deltas then we would like to see 3 or 4 decimals

**Comment by Eddman** [comment]
In this case I'm going to merge #59 and will put this issue to testing afterwards.

**Comment by Eddman** [comment]
@markadir Please verify and close the issue.

**Comment by Eddman** [comment]
@markadir Done. Check it out :+1:

**Comment by markadir** [comment]
I still see "Variation premium payment", "PremPay" with 3 Digits...

**Comment by Eddman** [comment]
Sorry, my bad :smile:  Forget to change the templates as well...Now it should be fine. It's fixed now.

**Comment by markadir** [comment]
The precision has been changed as specified. The issue is closed.
