### ISSUE TITLE
Margin Requirements Overview: display big margin block elements for pools

### ISSUE THREAD

**Issue by markadir** [Deutsche-Boerse-Risk/DAVe-UI#33]
![dashboardbigelements](https://user-images.githubusercontent.com/23376525/28814361-8a022704-769d-11e7-94be-b9f31fdb9360.PNG)

**Comment by markadir** [comment]
We discussed with @iyigmel that it would make more sense to Show pool Level margin shortfalls, Surplus in the big blocks. You would have then in rows the big blocks per pool. The first column will be the poolname the second will be the margin Shortfall/Surplus in green or red and the last (after Cash Balance) would be the Details button where after clicking the NCMs/Accounts will be displayed.

![dashboard details](https://user-images.githubusercontent.com/23376525/28814601-894b4d6c-769e-11e7-945d-c047385b98c0.PNG)
  

The sorting of the bigger blocks will be by largest negative numbers on top ( Hence red blocks will be on top)

**Comment by iyigmel** [comment]
in the current version, shortfall/surpluss is shown only on CM level which does not make sense. We need to add pool information and display above figures for each pool

**Comment by Eddman** [comment]
@markadir, @iyigmel could you please add an example with columns to make it more clear for me? Thanks.

**Comment by markadir** [comment]
@Eddman I will try to make a graphical example with ppt next week.

**Comment by iyigmel** [comment]
https://github.com/Deutsche-Boerse-Risk/DAVe-UI/issues/34
please consider this issue as well....I added some proposals
@markadir @Eddman

**Comment by markadir** [comment]
@iyigmel : Please place the relevant proposals directly into the issue.

**Comment by Eddman** [comment]
Please consider also the problem in #42.

**Comment by markadir** [comment]
I don't really think it is a Problem if we continue summing over currency adjusted values if the sum is in the end EUR (Clearing Cur) and conversion was made to EUR. Initial Margin and LA values are in Clearing currency. Collateral values are also adjusted. Cash Balance should be in the Cash currency and we can add currency code behind all numbers. The only thing where it's not in Clearing currency is in the detailed table where Premium Margin and Variation/Premium Payment is in product currency but since we Show the currency right next to number it is transparent.

**Comment by markadir** [comment]
The use case is desribed here: [pull44](https://github.com/Deutsche-Boerse-Risk/DAVe-UI/pull/44)

**Comment by iyigmel** [comment]
[Issue_33_IT_Provided.xlsx](https://github.com/Deutsche-Boerse-Risk/DAVe-UI/files/1234129/Issue_33_IT_Provided.xlsx)

Adam please have a look into the attached file. I added the example

**Comment by Eddman** [comment]
@markadir, @iyigmel Do I understand it (based on the .xlsx) correctly that we're going to remove `Collateral` and that `Cash balance` should be computed based only on `Cash collateral amount`?

In the Deutsche-Boerse-Risk/DAVe-UI/pull/44 the `Collateral` is still there...

**Comment by Eddman** [comment]
@markadir Another question: in the #44 you're saying that once the detail is clicked a table should be shown:
```
Details of all clients and accounts associated to the pool appear
```
![image](https://user-images.githubusercontent.com/209500/29621266-8667eafe-8820-11e7-9570-fed2349edee2.png)

But where should I get such data? There are just two aggregation levels where we have the pool name available. I have either Account margin data: 
```
{
    clearer: string;
    member: string;
    account: string;
    marginCurrency: string;
    clearingCurrency: string;
    pool: string;
    marginReqInMarginCurr: number;
    marginReqInClrCurr: number;
    unadjustedMarginRequirement: number;
    variationPremiumPayment: number;
}
```
Ot the Pool margin data:
```
{
    clearer: string;
    pool: string;
    marginCurrency: string;clrRptCurrency: string;
    requiredMargin: number;
    cashCollateralAmount: number;
    adjustedSecurities: number;
    adjustedGuarantee: number;
    overUnderInMarginCurr: number;
    overUnderInClrRptCurr: number;
    variPremInMarginCurr: number;
    adjustedExchangeRate: number;
    poolOwner: string;
}
```

**Comment by markadir** [comment]
@iyigmel Maybe we should just Show here the current pool margin Details table? What do you think?

**Comment by Eddman** [comment]
The first prototype:
![image](https://user-images.githubusercontent.com/209500/29621520-43868b04-8821-11e7-9067-113300ab0f04.png)

**Comment by Eddman** [comment]
@markadir, @iyigmel And what about the first question? (https://github.com/Deutsche-Boerse-Risk/DAVe-UI/issues/33#issuecomment-324052289)

**Comment by markadir** [comment]
I would leave collateral. It should be clear MarginSurplus = Collateral - MarginRequireement. And Cash Balance Shows the amount of Cash in the collateral, hence rest is non cash. Very usefull Information set.

**Comment by Eddman** [comment]
@markadir, @iyigmel Could you please update the XLSX (https://github.com/Deutsche-Boerse-Risk/DAVe-UI/issues/33#issuecomment-323319304) with the desired aggregations? Thanks.

**Comment by Eddman** [comment]
@markadir So we'll remove the last button and add the Collateral box back... :smile:

**Comment by markadir** [comment]
All of the numbers should be currency converted though... I though @iyigmel will provide you with the source where you have all values already converted?

**Comment by Eddman** [comment]
@markadir We had a discussion over phone about that and @iyigmel is convinced that th FX rates are just fine to calculate the result from Pool Margin without additional report from Prisma...

**Comment by markadir** [comment]
Well then everything should be clear now. Full steam ahead!

**Comment by Eddman** [comment]
@markadir Except the missing updated XLSX for `Collateral`...

**Comment by markadir** [comment]
[Issue_33_IT_Provided.xlsx](https://github.com/Deutsche-Boerse-Risk/DAVe-UI/files/1251709/Issue_33_IT_Provided.xlsx) I have added the collateral formula.

**Comment by Eddman** [comment]
@markadir Last thing: do you want to sort the different pools somehow? Eg. with negative `Cash balance` first, etc...

**Comment by iyigmel** [comment]
Hi Adam, in my previous email formula for overall colateral was missing. I slightly changed the calculation from @markadir ....
please find attached file with the corrected colleteral calculation... I already clarified with Marat...

In addition to this  it would make sense to sort pools descending order in MarginShortfall/Surplus

**Comment by Eddman** [comment]
@markadir, @iyigmel Please verify and close the issue.

**Comment by markadir** [comment]
verified. Please resize the pool button. The issue can be closwd.
