### ISSUE TITLE
Check wording/spelling and consistency

### ISSUE THREAD

**Issue by markadir** [Deutsche-Boerse-Risk/DAVe-UI#35]
Go through the application and check for spelling or wording issues. Additionally check if column names are named consistently and describing the right data.

DoD:

- [x] The application has correct and proper language, tool tips describe columns correctly

- [x] All column names are consistent   

- [x] Column description and values are consistent

**Comment by markadir** [comment]
Solution for some of the wording/spelling issues is described by [Issue #36](https://github.com/Deutsche-Boerse-Risk/DAVe-UI/issues/36). Issue 36 can be closed if the Points are implemented and this issue can remain in the back-log so we always have an issue for an ongoing check process.

**Comment by markadir** [comment]
Additional column name changes and improvements I found:
### Position Report
The scrolling is not very convenient if you are on details, since you first have to scroll down in order to scroll right.

- [ ] Add "Last relevant price" in details showing price of the instrument used for all the margin or greeks figure displayed 

- [ ] Change "PremMrgn" to Premium Margin for consistency

- [ ] Change all greeks column names to EuroGreek i.e. Vega to EuroVega

- [ ] Change "Strk" to "Strike"

### Initial Margin

- [ ] Change Liqu Risk to "Liquidity Add-on (LA)"

**Comment by Eddman** [comment]
@markadir 2 questions:
1) What do you mean by:
```
Add "Last relevant price" in details showing price of the instrument used for all
 the margin or greeks figure displayed
```
2) In #22 we have EUR Vega and here EuroVega. What should I use?

**Comment by markadir** [comment]
@Eddman 
1) For each of the margin calculations or EUR Delta there was a Price used. In EUREX_PRISMA.F_FCT_THEORETICALPRICE with RISK_MEASURE_SET_ID = -1
and SCENARIO_INDEX = -1 you find the Prices for each UIID and the same ARID as used for margin values the tool Shows.
2) Use EUR Vega, EUR Delta etc, since we use EUR everywhere

**Comment by Eddman** [comment]
@orsamir will add the price to the report as it is currently not sent from Prisma. I've created a separate issue #64 to track this as it is a bigger task.

**Comment by Eddman** [comment]
@markadir Please verify and close the issue.

**Comment by markadir** [comment]
The issue is implemented and can be closed.
