### ISSUE TITLE
Naming/labelling changes to be made

### ISSUE THREAD

**Issue by PavlaSip** [Deutsche-Boerse-Risk/DAVe-UI#36]
•	CopmError field under Position Reports: as this field shows the position Compression Error, it should be called CompError
•	Description of EuroDelta should be: Position sensitivity to underlying move in Euro
•	Variation / Premium Cash Flow should be renamed to Variation Premium Payment

**Comment by Eddman** [comment]
@PavlaSip Please verify and close the issue.

**Comment by PavlaSip** [comment]
Looks good to me, thanks! :)
