### ISSUE TITLE
Create Tooltips for Prisma specific metrics

### ISSUE THREAD

**Issue by markadir** [Deutsche-Boerse-Risk/DAVe-UI#38]
Tooltips have to be created for metrics that are not straight Forward and are expected not to be understood by an outside user.

**Comment by PavlaSip** [comment]
I would propose to add the following tooltips to the UI: 

 - Unadjusted margin: Total margin requirement in margin currency
 - NetEA: Net quantity of exercised / assigned options
 - CorrBreak: Correlation Break Add-on value of the position 
 - CompError: Compression Error of the position
 - LonOptCredit: Long Option Credit
 - MVaR: Position marginal VaR
 - Utilization: Current amount

**Comment by PavlaSip** [comment]
@hauehan @markadir @iyigmel: do you agree with the additional proposed tooltips above?

**Comment by PavlaSip** [comment]
@hauehan 
CompError: the full Name is in fact Compression Error Add-on so we can Display "Compression Error Add-on of the position"
I have updated the list above.

**Comment by hauehan** [comment]
Yes, this makes sense.

**Comment by Eddman** [comment]
@PavlaSip Please verify and close the issue.

**Comment by PavlaSip** [comment]
Looks good, thanks!
