### ISSUE TITLE
Initial Margin: add value/share in % to the member/client codes

### ISSUE THREAD

**Issue by PavlaSip** [Deutsche-Boerse-Risk/DAVe-UI#41]
@markadir @hauehan @iyigmel: should we add value or share in % to the member/Client codes in the Initial Margin view? It would make it more clear how much each member/Client contributes to the IM. 
![initialmarginsnapshot](https://user-images.githubusercontent.com/30694014/28969099-6eef7448-7923-11e7-856a-713a04c5a083.PNG)

**Comment by markadir** [comment]
@Eddman : How complicated is it to show the relative size of each block in %? You probably don't need to calculate it, since it's known to be able to show the graph at all.

**Comment by Eddman** [comment]
@markadir The relative size is calculated automatically by the chart library we're using, but it is no problem to calculate and display it for the label as well.

**Comment by markadir** [comment]
Then let's have the relative size of the risk below the Client Name as sub title.

**Comment by Eddman** [comment]
![image](https://user-images.githubusercontent.com/209500/29422002-1a8e68b0-8377-11e7-9a6c-1b0ddf98cd08.png)

This is closest I can get. There is restriction in the chart library that the label has to be on a single line. 

@PavlaSip Please verify and close the issue.

**Comment by markadir** [comment]
This Looks quite good to me. What do you mean "It's the Closest you can get"? Do the percentage values not add up to 100 :)

**Comment by Eddman** [comment]
@markadir Obviously I mean the label in a single line :smile:

**Comment by PavlaSip** [comment]
Looks good, thank you. One question though - when I drill down on e.g. FOXOS-PP which is 21% on the first Level, the next view I get does not add up to 100 anymore but only to the 21% - so that we still refer to the Portion of Initial Margin of the whole clearer and not the selected account. Does this make sense or should we rather display the % relative to the level we are on? (e.g. % of LG per account)

**Comment by hauehan** [comment]
Change back so that each level adds up to 100%.

**Comment by Eddman** [comment]
@PavlaSip Please verify and close the issue.

**Comment by PavlaSip** [comment]
@Eddman Looks good! One question - if it adds up to 99,9 I assume this is because rounding differences, correct?

**Comment by Eddman** [comment]
Exactly. The floats have only limited precision so some times when rounding is done we loose a bit of it :)
