### ISSUE TITLE
Add the "Total Margin" column into the chart on Margin Compoents History view

### ISSUE THREAD

**Issue by scholzj** [Deutsche-Boerse-Risk/DAVe-UI#5]
Add the "Total Margin" column into the chart on Margin Compoents History view as discussed in Deutsche-Boerse-Risk/DAVe#28

**Comment by Eddman** [comment]
@scholzj We have "Additional Margin" chart column that is showing the same data as "Total Margin" column in the table. Do we just change the name? Or do we have a bug here and "Total Margin" column in the table is incorrect and we should show different data/header?

**Comment by scholzj** [comment]
Ok, now I understand ... Variation and Liquidation margin is merged into single line - and total margin is named additional margin. That is why its confusing. Could you please rename the line / button? Thanks.

**Comment by Eddman** [comment]
Renamed.
