### ISSUE TITLE
Number of positions in Position Level Risk

### ISSUE THREAD

**Issue by hauehan** [Deutsche-Boerse-Risk/DAVe-UI#55]
"20 top risk positions represent 185.96% of total portfolio VaR. 20 top offsetting positions represent 100.00% of total offsetting positions. Total portfolio VaR is 504,757.94 EUR."

20 should reflect actual number of positions capped at 20.

**Comment by Eddman** [comment]
@markadir, @PavlaSip: Please verify and close the issue.

**Comment by PavlaSip** [comment]
I looked at it and technically I would say it's working well - i.e. showing always the real number of positions capped at 20. However, I am not sure the first sentence makes sense, it seems a bit odd to say "6  top risk positions represent  13,115.99% of total portfolio VaR" (for AKWLT)... How is it calculated? Does it take the individual values of positions and sums up?

**Comment by markadir** [comment]
It's the sum of top 6 compVar. I think it makes a lot of sence. If I have 100 positions and 1 Future is the hedge I want to see that. If I have only 6 positions and they are all in one direction I want to see that as well.

**Comment by markadir** [comment]
Verified and will be closed.
