### ISSUE TITLE
The Filter Functionality does not work

### ISSUE THREAD

**Issue by markadir** [Deutsche-Boerse-Risk/DAVe-UI#57]
On any report page if a User enters something into the Filter field, like member or "EUR" in Accoun Margin Page the filter is not apllied.

**Comment by Eddman** [comment]
@markadir I don't see any problem here. "EUR" is the clearing ccy. So each row has it :smile:. Try "CHF" for instance. The same if I write "FOX" it filters only "FOXOS" member.

**Comment by markadir** [comment]
I see, it works but not for VGWTT. I assume it's because he is the CM?

**Comment by Eddman** [comment]
Yes, VGWTT is in this case the clearer :+1:

**Comment by markadir** [comment]
But how can you then view only clearer accounts? If you only want to see the clearer as NCM?

**Comment by Eddman** [comment]
You have to click on the NCM, the filter won’t help in such case.
-----------------------------------------
Diese E-Mail enthaelt vertrauliche oder rechtlich geschuetzte Informationen.
Wenn Sie nicht der beabsichtigte Empfaenger sind, informieren Sie bitte
sofort den Absender und loeschen Sie diese E-Mail. Das unbefugte Kopieren
dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen
ist nicht gestattet.

The information contained in this message is confidential or protected by
law. If you are not the intended recipient, please contact the sender and
delete this message. Any unauthorised copying of this message or
unauthorised distribution of the information contained herein is prohibited.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

**Comment by markadir** [comment]
The invisible column should not be taken into account for the filter.

**Comment by Eddman** [comment]
@markadir The filter is now working only over visible columns. Please check and close the issue.

**Comment by markadir** [comment]
verified - closing the issue
